# Generated by Django 4.1 on 2023-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completionPercentage',
            field=models.IntegerField(default=0),
        ),
    ]
